name: Build My Print Store Frontend App and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: mytest

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install --force

    - name: Build App
      run: npm run build

    - name: Copy Build to Server
      uses: appleboy/scp-action@v0.1.4      
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "./dist"
        target: /var/www/myprintstore/
