name: CI/CD for printsource frontend

on:
  push:
    branches:
      - metaData

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: dev

    - name: Run Script on the Server
      uses: appleboy/ssh-action@v1.0.2      
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PASSWORD }}  
        script: |
          cd my-print-source-frontend/
          git pull origin metaData
          docker-compose up --build -d
